spring:
  application:
    name: todotask

  datasource:
    url: jdbc:mysql://localhost:3306/artemise?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver